---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
  labels:
    app: userapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: jackjackzhou/user-api
          # imagePullPolicy: Never
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: user-app-key
              mountPath: “/app”
              readOnly: true
      volumes:
        - name: user-app-key
          secret:
            secretName: user-app-key

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: userapi
  type: LoadBalancer